### ISSUE TITLE
UMD export using wrong package name

### ISSUE THREAD

**Issue by rdmurphy** [mapbox/potpack#1]
Hello! 👋  Was snooping around and noticed that it appears the `rollup.config.js` copy-pasted from `flatbush` still contains a reference to its export name for the UMD build.

https://github.com/mapbox/potpack/blob/797c0483726da8999e265b2b7f7487a7a9635ccd/rollup.config.js#L6

**Comment by mourner** [comment]
Oh damn 😂 Thanks for catching that!

**Comment by mourner** [comment]
Fixed in v1.0.1
