### ISSUE TITLE
Sort Messes up Id

### ISSUE THREAD

**Issue by jjwallace** [mapbox/potpack#2]
I am passing an object into - potpack(array)
array has a unique id,
I try to references is later
var id = this.nodes[i].group.id
var groupX = gridValues[id].x;

But it seems everything has been reorganized.
I thought the array its self and all its child keys would be mutated in a sort, is this correct?

**Comment by mourner** [comment]
Yes, the given array is sorted in-place. I'd suggest adding the `id` as a key to array items, and then passing a copy to potpack (`potpack(array.slice())`).
