### ISSUE TITLE
Get rectangles final positioning X,Y

### ISSUE THREAD

**Issue by caiusCitiriga** [mapbox/potpack#6]
Is it possible to get somehow the final position on the near square result of each box with X,Y coordinates?

**Comment by mourner** [comment]
The final positions (`x` and `y`) get added to the original input objects, as described in the readme: https://github.com/mapbox/potpack#example-usage

Unless I'm misunderstanding the question?

**Comment by caiusCitiriga** [comment]
@mourner No, sorry, me dumb. Didn't see that part. Thank you very much ❤️
