### ISSUE TITLE
Example does not work properly

### ISSUE THREAD

**Issue by barisyild** [mapbox/potpack#9]
### Original Example

```javascript
import potpack from 'potpack';

const boxes = [
    {w: 300, h: 50},
    {w: 100, h: 200},
    ...
];

const {w, h, fill} = potpack(boxes);
// w and h are resulting container's width and height;
// fill is the space utilization value (0 to 1), higher is better

// potpack mutates the boxes array: it's sorted by height,
// and box objects are augmented with x, y coordinates:
boxes[0]; // {w: 300, h: 50,  x: 100, y: 0}
boxes[1]; // {w: 100, h: 200, x: 0,   y: 0}
```
Example usage is as above but real world tests are further below.

### Test from Github Source Code

```javascript
import potpack from 'potpack';

const boxes = [
    {w: 300, h: 50},
    {w: 100, h: 200},
    ...
];

const {w, h, fill} = potpack(boxes);
// w and h are resulting container's width and height;
// fill is the space utilization value (0 to 1), higher is better

// potpack mutates the boxes array: it's sorted by height,
// and box objects are augmented with x, y coordinates:
boxes[0]; // {w: 100, h: 200, x: 0, y: 0}
boxes[1]; // {w: 300, h: 50, x: 0, y: 200}
```

The important difference in the 2th example is that the order changes so it is not possible to distinguish without an id system.

Why is there such a difference, is the code in the git repo broken?

**Comment by barisyild** [comment]
Current Developer Console output is attached

![image](https://github.com/mapbox/potpack/assets/25794892/c0eee892-8ef2-471f-bbef-2bf080562823)

**Comment by mourner** [comment]
This is by design. Here's a quote from the README:

> // potpack mutates the boxes array: it's sorted by height,
> // and box objects are augmented with x, y coordinates:

How you deal with this is up to you — sometimes you index by id, and sometimes there's no need to identify the objects as long as you can iterate over all of them. It depends on the use case. I don't think there's anything I should change in the docs, but if you feel differently, I'm up for suggestions.
